"""Python implementation scaffold for MetaInsight.

This package provides a clean-room, Python-first foundation for the core
MetaInsight workflows. The API mirrors the existing R package entry points
in a progressive way so features can be ported module-by-module.
"""

from .core import MetaInsightBundle, MetaInsightConfig, load_data
from .setup import (
    ConfiguredData,
    ExcludedData,
    LoadedData,
    ValidationResult,
    clean_data,
    setup_configure,
    setup_exclude,
    setup_load,
    setup_upgrade,
    validate_uploaded_data,
)
from .frequentist import (
    create_list_of_wide_columns,
    contrast_form,
    freq_compare,
    freq_forest,
    freq_forest_limits,
    freq_forest_annotation,
    freq_inconsistent,
    freq_summary,
    frequentist,
)
from .covariate import (
    CovariateModel,
    calculate_credible_regions,
    calculate_directness,
    covariate_model,
    covariate_regression,
    covariate_summary,
    find_covariate_ranges,
)
from .baseline import (
    LitmusRankOGram,
    RadialSUCRA,
    baseline_comparison,
    baseline_deviance,
    baseline_details,
    baseline_forest,
    baseline_forest_limits,
    baseline_mcmc,
    baseline_model,
    baseline_ranking,
    baseline_regression,
    baseline_results,
    baseline_summary,
    bayes_compare,
    bayes_deviance,
    bayes_details,
    bayes_forest,
    bayes_mcmc,
    bayes_nodesplit,
    bayes_nodesplit_plot,
    bayes_ranking,
    bayes_results,
    covariate_comparison,
    covariate_deviance,
    covariate_details,
    covariate_forest,
    covariate_mcmc,
    covariate_ranking,
    covariate_results,
    density_plots,
    format_baseline_forest,
    gelman_plots,
    metaregression_plot,
    ranking_table,
    trace_plots,
)
from .network import (
    create_graph,
    find_all_treatments,
    find_studies_including_treatments,
    identify_subnetworks,
    is_nodesplittable,
)

__all__ = [
    "MetaInsightBundle",
    "MetaInsightConfig",
    "load_data",
    "setup_configure",
    "setup_exclude",
    "setup_load",
    "setup_upgrade",
    "ConfiguredData",
    "ExcludedData",
    "LoadedData",
    "ValidationResult",
    "clean_data",
    "validate_uploaded_data",
    "create_graph",
    "find_all_treatments",
    "find_studies_including_treatments",
    "identify_subnetworks",
    "is_nodesplittable",
    "calculate_credible_regions",
    "calculate_directness",
    "covariate_model",
    "covariate_regression",
    "covariate_summary",
    "find_covariate_ranges",
    "baseline_comparison",
    "baseline_deviance",
    "baseline_details",
    "baseline_forest",
    "baseline_forest_limits",
    "baseline_mcmc",
    "baseline_model",
    "baseline_ranking",
    "baseline_regression",
    "baseline_results",
    "baseline_summary",
    "bayes_compare",
    "bayes_deviance",
    "bayes_details",
    "bayes_forest",
    "bayes_mcmc",
    "bayes_nodesplit",
    "bayes_nodesplit_plot",
    "bayes_ranking",
    "bayes_results",
    "covariate_comparison",
    "covariate_deviance",
    "covariate_details",
    "covariate_forest",
    "covariate_mcmc",
    "covariate_ranking",
    "covariate_results",
    "density_plots",
    "format_baseline_forest",
    "gelman_plots",
    "LitmusRankOGram",
    "metaregression_plot",
    "RadialSUCRA",
    "ranking_table",
    "trace_plots",
    "CovariateModel",
    "create_list_of_wide_columns",
    "contrast_form",
    "freq_compare",
    "freq_forest",
    "freq_forest_annotation",
    "freq_forest_limits",
    "freq_inconsistent",
    "freq_summary",
    "frequentist",
]

__version__ = "0.1.0"
